config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    member do
      get :file
      get :modal
    end
  end
  resources :comments, :only => [:show, :create, :destroy]
  
end

app/helpers/posts_helper.rb
module PostsHelper
  def comments_link_text(post)
    post.comments.count.zero? ? 'Write the first comment' : "#{pluralize(post.comments.count, 'user')} commented"
  end
end

app/views/comments/_comment.html.haml
.comment{ id: "comment#{comment.id}", class: comment == @comment ? 'active' : '' }
  -if can?(:destroy, comment)
    =link_to('', comment, method: :delete, confirm: 'Are you sure?', remote: true, class: 'comment-delete-link', icon: 'trash-o')
  =link_to(image_for(comment.user, '40x40#'), comment.user, class: 'comment-image' )
  .comment-text
    =link_to_self(comment.user)
    %span.small-info-text
      replied
      =time_ago_in_words(comment.created_at) + ' ago'
    %br
    =comment.text
  .clear

app/views/comments/_form.html.haml
.comment-form
  =link_to(image_for(current_user, '40x40#'), current_user, class: 'comment-image')
  =semantic_form_for(comment, remote: true, html: { class: 'loader-long' }) do |form|
    =form.hidden_field :post_id
    =form.inputs do
      =form.input :text, label: false, input_html: { rows: 1, placeholder: 'Write a comment...', id: '', class: 'autogrow-short' }

app/views/comments/create.js.erb
<%if @comment.errors.empty?%>
  $('#post<%=@comment.post_id%> .comment-list').append('<%=escape_javascript(render('comments/comment', :comment => @comment))%>')
  <%@comment = Comment.new(:post_id => @comment.post_id, :user_id => @comment.user_id)%>
<%end%>
$('#post<%=@comment.post_id%> .comment-form').replaceWith('<%=escape_javascript(render('comments/form', :comment => @comment))%>')

app/views/comments/destroy.js.erb
$(".comments .comment#comment<%=@comment.id%>").fadeOut('fast', function() {
  $(this).remove();
});

app/views/posts/_post.html.haml
.post.mb-2{ id: "post#{post.id}" }
  .post-top
    .pull-left
      =link_to(image_for(post.user, '40x40#'), post.user)
      =link_to_self(post.user)
      -if post.target
        %i.fa.fa-chevron-right
        =link_to_self(post.target)
      %br
      %time{ datetime: post.created_at.strftime('%Y-%m-%d') }
        %span.small-info-text
          =time_ago_in_words(post.created_at)
          ago
    =link_if_can('', [:destroy, post], method: :delete, confirm: 'Are you sure?', remote: true, icon: 'trash-o', class: 'post-delete')
    .clear
  -if post.text.present? || post.file
    .post-content
      -if post.text.present?
        =simple_format(auto_link(post.text))
      -if post.file
        =link_if_can([:file, post]) do
          %i{ class: "fa fa-file-#{post.file_ext}-o" }
          =post.file_name
  -if post.image
    .post-image
      =link_to('#', data: { toggle: 'modal', backdrop: false, modal_url: modal_post_path(post), modal_id: 'post_modal' }) do
        =image_for(post, '750x400#', class: "#{ post.has_video? ? 'video-image' : '' }")
    -if post.has_video? && post.video_title.present?
      .post-content
        =link_to(post.video_title, "#", :data => { toggle: 'modal', backdrop: false, modal_url: modal_post_path(post), modal_id: 'post_modal' })
        %br
        =link_to(post.video_youtube? ? 'youtube.com' : 'vimeo.com', post.video_url, target: '_blank', class:  'small-info-text')
        -if post.video_description.present?
          %p=strip_tags(post.video_description)
    .clear
  -if post.tags.present?
    .post-tags.mb-1
      -post.tags.each do |tag|
        =link_to_tag(tag, class: 'pull-left mr-1')
    .clear
  .comments
    =link_to(comments_link_text(post), '#', class: 'toggle-comments', icon: 'comments')
    .comment-list
      =render(partial: 'comments/comment', collection: post.comments)
    -if can?(:new, Comment)
      =render('comments/form', comment: post.comments.build)

app/views/posts/_posts.html.haml
=# For pagination: needs a <action_name>.js.erb file for the action this partial is used on. Which replaces .posts div e.g. posts/index.js.erb
.posts.loader-long
  -posts.each do |post|
    =render("posts/post", :post => post)
  .clearfix
  =will_paginate(posts, :remote => true)

app/views/posts/_remote_form.html.haml
-if can?((post.new_record? ? :create : :update), post)
  =semantic_form_for(post, format: :js, remote: true, multipart: true, html: { class: "post_form#{post.errors.present? ? ' expanded' : ''}" }) do |form|
    =form.inputs do
      =form.hidden_field :target_type
      =form.hidden_field :target_id
      =form.hidden_field :retained_image
      =form.hidden_field :retained_file
      %ul.nav.nav-tabs
        %li.active=link_to('Write', '#write', data: { toggle: :tab }, icon: 'pencil')
        %li=link_to('Image', '#image', data: { toggle: :tab }, icon: 'camera')
        %li=link_to('Video', '#video', data: { toggle: :tab }, icon: 'video-camera')
        %li=link_to('File', '#file', data: { toggle: :tab }, icon: 'file')
      .tab-content
        #write.tab-pane.fade.in.active
          =form.input :text, label: false, input_html: { rows: 3, placeholder: 'Post something' }, class: 'mb-0'
        #image.tab-pane.fade
          =form.input :image, as: :file, label: false
        #video.tab-pane.fade
          =form.input :video_url, label: false, input_html: { placeholder: 'URL from YouTube or Vimeo' }
        #file.tab-pane.fade
          =form.input :file, as: :file, label: false
      .not-expanded
        =form.input :tag_list, label: false, input_html: { placeholder: 'Tags', data: { autocomplete: autocomplete_tags_path, delimiter: ', ' }}
        =form.action :submit, label: 'Post', button_html: { class: 'btn btn-primary pull-right mb-1', data: { loading_text: 'Posting...' }}

app/views/posts/create.js.erb
  $('form#new_post').replaceWith('<%=escape_javascript(render('posts/remote_form', :post => (@new_post || @post)))%>');
  <%if @post.valid?%>
    $('div.posts').prepend('<%=escape_javascript(render('posts/post', :post => @post))%>');
    $(".comment-form textarea").autogrow();
  <%end%>

app/views/posts/destroy.js.erb
$(".posts .post#post<%=@post.id%>").fadeOut();

app/views/posts/index.html.haml
.container
  .row
    .span8
      %h1=title("Latest posts")
  .row
    .span8
      -if can?(:create, Post)
        =render("posts/remote_form", :post => current_user.posts.build)
      =render("posts/posts", :posts => @posts)

app/views/posts/index.js.erb
$('.posts').html('<%=escape_javascript(render('posts/posts', :posts => @posts))%>').removeClass('loading');

app/views/posts/modal.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      %button.close{aria: { hidden: true }, data: { dismiss: 'modal' }, type: 'button' } &times;
    .modal-body.center
      -if @post.has_video?
        %iframe{ width: 853, height: 480, src: @post.video_embed_url, frameborder: 0, allowfullscreen: true}
      -else
        =image_for(@post, '880x>')

app/views/posts/show.html.haml
-if @comment
  -content_for(:head) do
    :coffeescript
      $ ->
        YmCore.scrollTo('#comment#{@comment.id}')

-title("#{@post.user.first_name}'s post")
=render("posts/post", :post => @post)